version: '3'
services:
  app:
    &app
    build: .
    volumes:
      - .:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: sh -c "bundle install"
  tests:
    <<: *app
    command: sh -c "bundle install && rspec && rubocop --lint"
